create extension if not exists pgcrypto;

create table if not exists public.flight_watches (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  origin text not null check (origin ~ '^[A-Z]{3}$'),
  origin_city text not null check (char_length(origin_city) between 1 and 40),
  destination text not null check (destination ~ '^[A-Z]{3}$'),
  destination_city text not null check (char_length(destination_city) between 1 and 40),
  departure_date date not null,
  return_date date not null,
  search_mode text not null default 'exact',
  travel_month date,
  trip_days_min smallint,
  trip_days_max smallint,
  target_price integer not null check (target_price between 1 and 1000000),
  currency text not null default 'TWD' check (currency = 'TWD'),
  adults smallint not null default 1 check (adults between 1 and 9),
  cabin text not null default 'economy' check (cabin in ('economy','premium_economy','business','first')),
  nonstop boolean not null default false,
  active boolean not null default true,
  current_price integer,
  previous_price integer,
  offer_count integer not null default 0,
  provider text,
  search_url text,
  last_checked_at timestamptz,
  last_error text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (return_date > departure_date)
);

alter table public.flight_watches add column if not exists search_mode text not null default 'exact';
alter table public.flight_watches add column if not exists travel_month date;
alter table public.flight_watches add column if not exists trip_days_min smallint;
alter table public.flight_watches add column if not exists trip_days_max smallint;

do $$
begin
  if not exists (select 1 from pg_constraint where conname = 'flight_watches_search_mode_check') then
    alter table public.flight_watches add constraint flight_watches_search_mode_check check (search_mode in ('exact', 'month'));
  end if;
  if not exists (select 1 from pg_constraint where conname = 'flight_watches_flexible_dates_check') then
    alter table public.flight_watches add constraint flight_watches_flexible_dates_check check (
      search_mode = 'exact' or (
        travel_month is not null and
        trip_days_min between 1 and 30 and
        trip_days_max between trip_days_min and 30
      )
    );
  end if;
end $$;

create table if not exists public.watch_prices (
  id bigint generated by default as identity primary key,
  watch_id uuid not null references public.flight_watches(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  price integer not null check (price > 0),
  checked_at timestamptz not null default now(),
  provider text,
  unique (watch_id, checked_at)
);

create table if not exists public.user_preferences (
  user_id uuid primary key references auth.users(id) on delete cascade,
  email_alerts boolean not null default true,
  browser_alerts boolean not null default false,
  price_drop_percent smallint not null default 10 check (price_drop_percent between 1 and 90),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists flight_watches_user_id_idx on public.flight_watches(user_id);
create index if not exists flight_watches_active_idx on public.flight_watches(active, departure_date);
create index if not exists watch_prices_watch_checked_idx on public.watch_prices(watch_id, checked_at desc);

alter table public.flight_watches enable row level security;
alter table public.watch_prices enable row level security;
alter table public.user_preferences enable row level security;

drop policy if exists "Users manage own watches" on public.flight_watches;
create policy "Users manage own watches" on public.flight_watches for all to authenticated using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);
drop policy if exists "Users view own prices" on public.watch_prices;
create policy "Users view own prices" on public.watch_prices for select to authenticated using ((select auth.uid()) = user_id);
drop policy if exists "Users manage own preferences" on public.user_preferences;
create policy "Users manage own preferences" on public.user_preferences for all to authenticated using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);

grant select, insert, update, delete on public.flight_watches to authenticated;
grant select on public.watch_prices to authenticated;
grant select, insert, update, delete on public.user_preferences to authenticated;
grant all on public.flight_watches, public.watch_prices, public.user_preferences to service_role;
grant usage, select on sequence public.watch_prices_id_seq to service_role;

create or replace function public.set_updated_at()
returns trigger language plpgsql security invoker set search_path = '' as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists set_flight_watches_updated_at on public.flight_watches;
create trigger set_flight_watches_updated_at before update on public.flight_watches for each row execute function public.set_updated_at();
drop trigger if exists set_user_preferences_updated_at on public.user_preferences;
create trigger set_user_preferences_updated_at before update on public.user_preferences for each row execute function public.set_updated_at();
